AllCops:
  Exclude:
    - 'db/development.rb'
    - 'db/test.rb'
    - 'db/production.rb'

Metrics/LineLength:
  Exclude:
    - 'spec/spec_helper.rb'

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
